<?php

namespace SaQle\Core\Config;

use SaQle\Auth\Models\{BaseRole, BasePermission, BaseTenant, BaseUser};

final class ConfigDefaults{
     public static function merge(array $config): array {
         return array_replace_recursive(self::defaults(), $config);
     }

     private static function defaults(): array {
         return [
             //Enable role based accesscontrol with the following flags.
             'enable_rbac' => false,

             //the model for roles
             'role_model_class' => BaseRole::class,

             //the model for permissions
             'permission_model_class' => BasePermission::class,

             //an array of database context classes
             'db_context_classes' => [],

             //display error settings
             'display_errors' => 0,
             'display_startup_errors' => 0,

             //document root
             'document_root' => '', //-----------------------

             //application root domain
             'root_domain' => '', //---------------------

             /**
             * List of all the apps/modules in the project. 
             * A module/app is generally a folder with controllers, templates and routes
             * */
             'installed_apps' => [],

             /**
             * Default primary key type
             * Options [GUID, AUTO]
             * Override this for a given model with PrimaryKey attribute on a model property passing in the type in the constructor
             * GUID values will be auto generated before insert, while AUTO values are generated by the db engine on insert
             * */
             'primary_key_type' => 'GUID',

             /**
             * The model class name for authentications 
             * This class must be of type User.
             * */
             'auth_model_class' => BaseUser::class,

             /**
              * The following flags will enable or disable multitenancy
              * 1. TENANT_MODEL_CLASS  : the clas name of the tanant 
              * 2. ENABLE_MULTITENANCY : Expliclty set this to enable multi tenancy
              * */
             'tenant_model_class' => BaseTenant::class,
             'enable_multitenancy' => false,

             //The name of the root media folder. This is where all uploads will be saved to.
             'media_folder' => 'media',

             //the url prefix for media
             'media_url' => '/media/',

             //the url prefix for cron jobs
             'cron_url' => '/cron/',

             //the media url encryption key for secure file access
             'media_key' => '',

             //Set whether the media folder should live outside the webroot or in the webroot.
             'hidden_media_folder' => false,

             //API url prefixes
             'api_url_prefixes' => ['/api/v1/', '/api/v2/'],

             //SSE url prefixes
             'sse_url_prefixes' => ['/sse/v1/', '/sse/v2/'],

             //Date and time settings
             'date_added_format' => 'jS M Y',
             'date_display_format' => 'jS M Y',
             'datetime_display_format' => 'jS M Y h:s:m a',
             'default_timezone' => 'Africa/Nairobi',
             'system_date_format' => 'd-m-Y',

             //Session settings
             'cookie_domain' => '',
             'session_handler' => '',

             //Email settings
             'email_username' => '',
             'email_password' => '',
             'email_host' => '',
             'email_port' => 587,
             'email_sender_name' => '',
             'email_sender_address' => '',

             //System administrator
             'system_admin_email' => '',
             'system_admin_name' => '',

             /**
              * 1. Handling db column of type timestamp
              * 2. These flags can also be set on a model's meta array, and if that's the case, will override the values set here
              * */
             'db_auto_init_timestamp' => true,
             'db_auto_update_timestamp' => true,

             /**
              * 1. Set which type of time and/or date entry you want for created and modified at field for your models.
              * 2. This flag can also be set on a model's meta array, and if that's the case, will override the value set here.
              * Options: DATE, DATETIME, TIME, TIMESTAMP, PHPTIMESTAMP.
              * 
              * Defaults to PHPTIMESTAMP
              * */
             'db_auto_cmdt_type' => 'PHPTIMESTAMP',

             /**
              * When creating models, usually you want to keep track of 
              * 1. Who added a row
              * 2. Who modified a row
              * 3. Who deleted a row
              * 4. When was a row added
              * 5. When was a row modified
              * 6. When was a row deleted
              * 
              * The settings below will enable automatic inclusion of these fields without explicitly defining them 
              * in all the models.
              * 
              * MODEL_AUTO_CM_FIELDS
              * - This flag tells the model to generate Created By and Modified By fields. The field type will be GUID or AUTO(INT)
              *   depending on what the PRIMARY_KEY_TYPE flag is set to.
              * - The specific names of the fields will be set by adding the flags MODEL_CREATED_BY_FIELD and MODEL_MODIFIED_BY_FIELD
              * 
              * MODEL_AUTO_CMDT_FIELDS
              * - This flag tells the model to generate Created At and Modified At date/datetime/time/timestamp fields. The field type will be derived from
              *   the DB_AUTO_CMDT_TYPE flag
              * - The specific names of the fields will be set by adding the flags MODEL_CREATED_AT_FIELD and MODEL_MODIFIED_AT_FIELD
              * 
              * MODEL_SOFT_DELETE
              * - This flag tells the model to generate Is Deleted, Deleted By and Deleted At fields. The Deleted By type will
              *   deoend on the PRIMARY_KEY_TYPE flag and Deleted At type will depend on the DB_AUTO_CMDT_TYPE flag.
              * - The specific names of the fields will be set by adding the flags MODEL_DELETED_AT_FIELD and MODEL_DELETED_BY_FIELD and MODEL_DELETED_FIELD
              * 
              * All the flags below have model specific equivalents that can be used to override behavior from model to model
              * if that need arises.
              * */
             'model_auto_cm_fields' => false,
             'model_created_by_field' => 'added_by',
             'model_modified_by_field' => 'modified_by',

             'model_auto_cmdt_fields' => false,
             'model_created_at_field' => 'date_added',
             'model_modified_at_field' => 'last_modified',

             'model_soft_delete' => false,
             'model_deleted_at_field' => 'deleted_at',
             'model_deleted_by_field' => 'deleted_by',
             'model_deleted_field' => 'deleted',

             /**
              * What happens when duplicate data is encountered during insert or update operations.
              * 
              * Options include: 
              * ABORT_WITH_ERROR - Abort the insert or update operation and throw an exception
              * 
              * INSERT_MINUS_DUPLICATE - Insert only the data that is not duplicating
              * 
              * UPDATE_ON_DUPLICATE - Update the record that is already existing with incoming values and return the updated version.
              * 
              * RETURN_EXISTING - Return existing record(s) as it is. (alongside newly added ones if multiple records are being inserted)
              * 
              * Defaults to ABORT_WITH_ERROR
              * 
              * */
             'model_action_on_duplicate' => 'ABORT_WITH_ERROR',

             //During migrations, this class will be used to seed the database.
             'db_seeder' => '',

             /**
              * These models are resource models. Resource models are models that get
              * automatic resource controllers, views and routes for add, edit, delete, view actions.
              * */
             'resource_models' => [],

             /**
             * The directory in which class mappings will be cached. This is used by the framework and cannot be customized
             * at the moment
             * */
             'class_mappings_dir' => '/storage/framework/build/cache/mappings/',

             /**
             * The directory in which compiled views will be cached. This is used by the framework and cannot be customized
             * at the moment
             * */
             'templates_cache_dir' => '/storage/framework/build/cache/templates/',

             //The extension for component templates
             'component_template_ext' => 'html',

             /**
               * By default, components will be searched in the top level project directory, or inside
               * the individual app directories as listed in installed_apps. 
               * 
               * In cases where your components also exist in other places, list the directory
               * names here relative to the root directory.
             * */
             'extra_components_dirs' => [],

             'saqle_components_dir' => [realpath(__DIR__.'/../../components')],
         ];
     }
}
