<?php
namespace SaQle\Migration\Tracker;

class MigrationTracker{

    /**
     * A list of migration files ordered from earliest to latest. Migration files are executed in this order.
     * My tests have indicated that I cannot rely on the order that migration files were saved to disk is. 
     * */
	private array $migration_files = [];

    /**
     * A list of through models generated by manytomany fields defined on models.
     * This is a key => value array where
     * Key => the database context class name.
     * value => a key =>value array where key is the assigned table name and value is the full namespaced model class name.
     * */
    private array $through_models = [];

    public function add_migration(string $file_name){
    	 if(!in_array($file_name, $this->migration_files)){
    		 $this->migration_files[] = $file_name;
    	 }
    }

    public function get_migration_files(){
        return $this->migration_files;
    }

    public function set_through_models(array $models){
        $this->through_models = $models;
    }

    public function get_through_models() : array{
        return $this->through_models;
    }
}
?>