<?php
/**
 * This file is part of SaQle framework.
 * 
 * (c) 2018 SaQle
 * 
 * For the full copyright and license information, please view the LICENSE file
 * that was ditributed with the source code
 * */

/**
 * Represents a configuration object
 * 
 * @pacakge SaQle
 * @author  Wycliffe Omondi Otieno <wycliffomondiotieno@gmail.com>
 * */

namespace SaQle\Config;

class Config{
	 public function __construct(...$settings){
	 	/**
	 	 * Array of all the db context classes.
	 	 * */
	 	define("DB_CONTEXT_CLASSES", $settings['db_context_classes'] ?? []);

	 	/**
	 	 * Display errors
	 	 * */
	 	define("DISPLAY_ERRORS", $settings['display_errors'] ?? 0);
	 	define("DISPLAY_STARTUP_ERRORS", $settings['display_startup_errors'] ?? 0);

	 	 /**
	 	  * Project document root
	 	  * */
	 	 define("DOCUMENT_ROOT", $settings['document_root'] ?? $_SERVER['DOCUMENT_ROOT']);

         /**
          * App root domain
          * */
	 	 define("ROOT_DOMAIN", $settings['root_domain'] ?? $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].'/');

	 	 /**
	 	  * App base url
	 	  * */
	 	 define("BASE_URL", ROOT_DOMAIN);

	 	 /**
	 	  * Permission denied redirect url
	 	  * */
	 	 define("ACCESS_DENIED_REDIRECT_URL", $settings['access_denied_redirect_url'] ?? '');
	 	 define("RESOURCE_NOT_FOUND_REDIRECT_URL", $settings['resource_not_found_redirect_url'] ?? '');

		 /**
		  * List of all the apps/modules in the project. 
		  * A module/app is generally a folder with controllers, templates and routes
		  * */
	     define("INSTALLED_APPS", $settings['installed_apps'] ?? []);

		 /**
		 * Default primary key type
		 * Options [GUID, AUTO]
		 * Override this for a given model with PrimaryKey attribute on a model property passing in the type in the constructor
		 * GUID values will be auto generated before insert, while AUTO values are generated by the db engine on insert
		 * */
		 define("PRIMARY_KEY_TYPE", $settings['primary_key_type'] ?? 'GUID');

		 /**
		  * Model validation version to use.
		  * */
		 define("MODEL_VALIDATION_VERSION", $settings['model_validation_version'] ?? 1);

		 /**
		 * The model class name for authentications 
		 * This class must be of type User.
		 * */
		 define("AUTH_MODEL_CLASS", $settings['auth_model_class']);

		 /**
		 * The model class name for tenant 
		 * This class must be of type Tenant.
		 * */
		 define("TENANT_MODEL_CLASS", $settings['tenant_model_class'] ?? '');

		 /**
		 * The model class name for role 
		 * This class must be of type Role.
		 * */
		 define("ROLE_MODEL_CLASS", $settings['role_model_class']);

		 /**
		 * The authentication backend class
		 * */
		 define("AUTH_BACKEND_CLASS",  $settings['auth_backend_class']);

         /**
          * The name of the root media folder. This is where all uploads will be saved to.
          * */
		 define("MEDIA_FOLDER", $settings['media_folder'] ?? 'media');

		 /**
          * Set whether the media folder should live outside the webroot or in the webroot.
          * */
		 define("HIDDEN_MEDIA_FOLDER", $settings['hidden_media_folder'] ?? false);

		 /**
		  * API url prefixes
		  * */
		 define("API_URL_PREFIXES", $settings['api_url_prefixes'] ?? ['/api/v1/', '/api/v2/']);

		 /**
		  * Database settings
		  * */
		 define("DATABASE_USER",     $settings['database_user']     ?? '');
		 define("DATABASE_PASSWORD", $settings['database_password'] ?? '');
		 define("DATABASE_NAME",     $settings['database_name']     ?? '');
		 define("DATABASE_HOST",     $settings['database_host']     ?? 'localhost');

		 /**
		  * Date and time
		  * */
		 define("DATE_ADDED_FORMAT",       $settings['date_added_format']       ?? 'jS M Y');
		 define("DATE_DISPLAY_FORMAT",     $settings['date_display_format']     ?? 'jS M Y');
		 define("DATETIME_DISPLAY_FORMAT", $settings['datetime_display_format'] ?? 'jS M Y h:s:m a');
		 define("DEFAULT_TIMEZONE",        $settings['default_timezone']        ?? 'Africa/Nairobi');
		 define("SYSTEM_DATE_FORMAT",      $settings['system_date_format']      ?? 'd-m-Y');

		 /**
		  * Session settings
		  * */
		 define("SESSION_DOMAIN",  $settings['session_domain'] ?? $_SERVER['HTTP_HOST']);
		 define("SESSION_HANDLER", $settings['session_handler'] ?? '');

		 /**
		  * Email settings
		  * */
		 define("EMAIL_USERNAME",                 $settings['email_username']       ?? '');
		 define("EMAIL_PASSWORD",                 $settings['email_password']       ?? '');
		 define("EMAIL_HOST",                     $settings['email_host']           ?? '');
		 define("EMAIL_PORT",                     $settings['email_port']           ?? 587);
		 define("EMAIL_SENDER_NAME",              $settings['email_sender_name']    ?? '');
		 define("EMAIL_SENDER_ADDRESS",           $settings['email_sender_address'] ?? '');
		 define("WELCOME_EMAIL_SETUP_CLASS",      $settings['welcome_email_setup_class'] ?? '');
		 define("VERIFICATION_EMAIL_SETUP_CLASS", $settings['verification_email_setup_class'] ?? '');

		 /**
		  * System administrator
		  * */
		 define("SYSTEM_ADMINISTRATOR_EMAIL", $settings['system_admin_email'] ?? 'wycliffomondiotieno@gmail.com');
		 define("SYSTEM_ADMINISTRATOR_NAME",  $settings['system_admin_name']  ?? 'Wycliffe Omondi');
		 define("DI_CONTAINER",  dirname($_SERVER['DOCUMENT_ROOT'])."/saqle/services/container/container.php");
	 }
}
?>